export * from './interfaces/documentList';
export * from './interfaces/collectionList';
export * from './interfaces/databaseList';
export * from './interfaces/indexList';
export * from './interfaces/userList';
export * from './interfaces/sessionList';
export * from './interfaces/identityList';
export * from './interfaces/logList';
export * from './interfaces/fileList';
export * from './interfaces/bucketList';
export * from './interfaces/teamList';
export * from './interfaces/membershipList';
export * from './interfaces/functionList';
export * from './interfaces/installationList';
export * from './interfaces/providerRepositoryList';
export * from './interfaces/branchList';
export * from './interfaces/runtimeList';
export * from './interfaces/deploymentList';
export * from './interfaces/executionList';
export * from './interfaces/projectList';
export * from './interfaces/webhookList';
export * from './interfaces/keyList';
export * from './interfaces/platformList';
export * from './interfaces/countryList';
export * from './interfaces/continentList';
export * from './interfaces/languageList';
export * from './interfaces/currencyList';
export * from './interfaces/phoneList';
export * from './interfaces/variableList';
export * from './interfaces/proxyRuleList';
export * from './interfaces/localeCodeList';
export * from './interfaces/providerList';
export * from './interfaces/messageList';
export * from './interfaces/topicList';
export * from './interfaces/subscriberList';
export * from './interfaces/targetList';
export * from './interfaces/migrationList';
export * from './interfaces/firebaseProjectList';
export * from './interfaces/database';
export * from './interfaces/collection';
export * from './interfaces/attributeList';
export * from './interfaces/attributeString';
export * from './interfaces/attributeInteger';
export * from './interfaces/attributeFloat';
export * from './interfaces/attributeBoolean';
export * from './interfaces/attributeEmail';
export * from './interfaces/attributeEnum';
export * from './interfaces/attributeIp';
export * from './interfaces/attributeUrl';
export * from './interfaces/attributeDatetime';
export * from './interfaces/attributeRelationship';
export * from './interfaces/index';
export * from './interfaces/document';
export * from './interfaces/log';
export * from './interfaces/user';
export * from './interfaces/algoMd5';
export * from './interfaces/algoSha';
export * from './interfaces/algoPhpass';
export * from './interfaces/algoBcrypt';
export * from './interfaces/algoScrypt';
export * from './interfaces/algoScryptModified';
export * from './interfaces/algoArgon2';
export * from './interfaces/preferences';
export * from './interfaces/session';
export * from './interfaces/identity';
export * from './interfaces/token';
export * from './interfaces/jwt';
export * from './interfaces/locale';
export * from './interfaces/localeCode';
export * from './interfaces/file';
export * from './interfaces/bucket';
export * from './interfaces/team';
export * from './interfaces/membership';
export * from './interfaces/function';
export * from './interfaces/installation';
export * from './interfaces/providerRepository';
export * from './interfaces/detection';
export * from './interfaces/branch';
export * from './interfaces/runtime';
export * from './interfaces/deployment';
export * from './interfaces/execution';
export * from './interfaces/project';
export * from './interfaces/webhook';
export * from './interfaces/key';
export * from './interfaces/authProvider';
export * from './interfaces/platform';
export * from './interfaces/variable';
export * from './interfaces/country';
export * from './interfaces/continent';
export * from './interfaces/language';
export * from './interfaces/currency';
export * from './interfaces/phone';
export * from './interfaces/healthAntivirus';
export * from './interfaces/healthQueue';
export * from './interfaces/healthStatus';
export * from './interfaces/healthCertificate';
export * from './interfaces/healthTime';
export * from './interfaces/metric';
export * from './interfaces/metricBreakdown';
export * from './interfaces/usageDatabases';
export * from './interfaces/usageDatabase';
export * from './interfaces/usageCollection';
export * from './interfaces/usageUsers';
export * from './interfaces/usageStorage';
export * from './interfaces/usageBuckets';
export * from './interfaces/usageFunctions';
export * from './interfaces/usageFunction';
export * from './interfaces/usageProject';
export * from './interfaces/headers';
export * from './interfaces/proxyRule';
export * from './interfaces/smsTemplate';
export * from './interfaces/emailTemplate';
export * from './interfaces/consoleVariables';
export * from './interfaces/mfaChallenge';
export * from './interfaces/mfaRecoveryCodes';
export * from './interfaces/mfaType';
export * from './interfaces/mfaFactors';
export * from './interfaces/provider';
export * from './interfaces/message';
export * from './interfaces/topic';
export * from './interfaces/subscriber';
export * from './interfaces/target';
export * from './interfaces/migration';
export * from './interfaces/migrationReport';
export * from './interfaces/firebaseProject';
export * from './interfaces/attribute';
export * from './class';
export * from './realtime';

export type Payload = {
  [key: string]: any;
};

export type Headers = {
  [key: string]: string;
};
export type HttpMethods = 'GET' | 'HEAD' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';

export type UploadProgress = {
  $id: string;
  progress: number;
  sizeUploaded: number;
  chunksTotal: number;
  chunksUploaded: number;
};
